In [2]:
import torch

x = torch.empty(2)
print(x)
print(x.dtype)

x = torch.zeros(2, dtype=torch.float32)
print(x)
print(x.dtype)

x = torch.ones(3)
print(x)
print(x.dtype)

x = torch.rand(2, 2, 3)
print(x)
print(x.dtype)

tensor([0., 0.])
torch.float32
tensor([0., 0.])
torch.float32
tensor([1., 1., 1.])
torch.float32
tensor([[[0.8501, 0.5142, 0.4487],
         [0.5966, 0.4780, 0.8342]],

        [[0.5907, 0.6324, 0.4199],
         [0.9981, 0.3717, 0.7171]]])
torch.float32


In [3]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)

print(x)
print(y)

y.add_(x)
print(y)

y.mul_(x)
print(y)

y.div_(x)
print(y)
print(y[1, 1].item())

z = y.view(-1, 4)
print(z)

a = torch.rand(1, 1)
print(a)
print(a.item())

tensor([[0.5194, 0.3954],
        [0.5858, 0.6623]])
tensor([[0.1336, 0.5975],
        [0.4557, 0.8208]])
tensor([[0.6529, 0.9930],
        [1.0415, 1.4831]])
tensor([[0.3391, 0.3927],
        [0.6101, 0.9823]])
tensor([[0.6529, 0.9930],
        [1.0415, 1.4831]])
1.483107566833496
tensor([[0.6529, 0.9930, 1.0415, 1.4831]])
tensor([[0.0006]])
0.0005705952644348145


In [9]:
import numpy as np

a = torch.ones(5)
print(a)
print(a.dtype)
b = a.numpy()
print(b)

# If the tensor is on CPU and not on GPU, modifying one woulf modify the other
a.add_(1)
print(a)
print(b)

c = np.ones(5)
print(c)
d = torch.from_numpy(c)
print(d)

c += 1
print(c)
print(d)

tensor([1., 1., 1., 1., 1.])
torch.float32
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]
[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [14]:
import torch
import numpy as np

if torch.cuda.is_available():
    local_cude_device = torch.device("cuda")
    # creates tensor on GPU
    x = torch.ones(5, device=local_cude_device)

    # Create and move to GPU
    y = torch.ones(5)
    y = y.to(local_cude_device)

    # Tensor created on GPU
    z = x + y
    # Note: Numpy can only handle CPU tensors. Cannot convert GPU tensor to numpy
    z = z.to("cpu")
    print(z)
    print(z.numpy())

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [17]:
# This tells PyTorch that it needs to calculate gradients for this tensor later in your optimization steps
# Whenever you have a variable that you need to optimize, you will have to set this to True
p = torch.ones(5, requires_grad=True)
print(p)

tensor([1., 1., 1., 1., 1.], requires_grad=True)
